name: celsius_fahrenheit_converter
description: A simple Flutter app to convert Celsius to Fahrenheit using a TensorFlow Lite model.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/c_to_f_model.tflite
    - assets/f_to_c_model.tflite